## Downloading a Data Product

The last step is to download the product you have found. This all occurs under the `Product Download` tab, immediately after the `Product Catalog`. These downloads are based on a Product ID, and there are three different modes for download:

1. General— This mode downloads a product from one site without filtering over time. In other words, all dates available for a product-site combination are downloaded. This requires a Product ID and a Field Site.
2. Specific— This mode downloads a single product, site, and year-month combination (for example: Barometric pressure, SRER, 2018-09). A Product ID, Field Site, and date are required.
3. AOP— This mode is meant for AOP flight products. It downloads for a given Product ID, Field Site, and Year. By nature of AOP data, this will take a very long time.

Every download will go to a folder called `NEON Downloads`, which will be located outside of the directory containing this app (if the folder with this app is in the desktop, so is `NEON Downloads`). This section will explain all three modes of download. Click on the tabs below to navigate through the various topics:
