### Measuring the causes and effects of environmental change
The National Ecological Observatory Network is a continental-scale ecological observation facility, sponsored by the National Science Foundation and operated by Battelle. NEON collects and provides open data that characterize and quantify how our nation's ecosystems are changing. The comprehensive data, spatial extent and remote sensing technology provided by the NEON project will contribute to a better understanding and more accurate forecasting of how human activities impact ecology and how our society can more effectively address critical ecological questions and issues.

#### [NEON: Data to Understand Changing Ecosystems](https://youtu.be/39YrzpxVRF8)

<iframe width="640" height="360" src="https://www.youtube.com/embed/39YrzpxVRF8" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>

### NEON Provides Free and Publicly Accessible Resources
NEON data and resources are freely available to enable users to tackle scientific questions at scales not accessible to previous generations of ecologists. The observatory includes [81 field sites (47 terrestrial and 34 aquatic)](https://www.neonscience.org/field-sites/field-sites-map) located in different ecosystems across the United States (including Alaska, Hawaii and Puerto Rico). Data collection methods are standardized across sites and include [automated instrument measurements, observational field sampling and airborne remote sensing surveys.](https://www.neonscience.org/data-collection) Field sites are [strategically selected](https://www.neonscience.org/observatory/about/spatiotemporal-design) to represent different regions of vegetation, landforms, climate, and ecosystem performance. The NEON data catalog includes 181 data products.

NEON's primary purpose is to provide:

* [Continental-scale environmental data](https://www.neonscience.org/data/neon-data-portal)

* [Infrastructure for research](https://www.neonscience.org/resources/information-researchers)

* [Educational tools to work with large data](https://www.neonscience.org/opportunities/learning-opportunities)

### Current Status of the NEON Project
The planning and design of the NEON project was completed in early 2012. Construction of the observatory and field sites began soon after in Spring 2012. Currently, construction of the final few field sites for NEON is underway and the observatory has entered initial operations. NEON is expected to enter full operations by the early 2019 and collect data for 30 years. Preliminary data are already available for most of our data products, and data continue to be added to the NEON data portal weekly for users to download.

NEON is part of a bold effort to:

* Understand and forecast continental-scale environmental change

* Inform natural resource decisions

* Engage the next generation of scientists
